### ISSUE TITLE
build image operation failed

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/ks-devops#154]
**Describe the Bug**

**steps:**
1. When building the image,  select the correct mirror key 
2. Upload the correct WAR package
3. see result of the build mirror operation

**Expected results:**
The image can be successfully built

**Actual results:**
The build image failed, and no log information is displayed

![image](https://user-images.githubusercontent.com/36271543/112960953-81380500-9177-11eb-9c7d-809d7db672f2.png)

/kind bug
/assign @LinuxSuRen
/priority High
/milestone 3.1.0

**Comment by JohnNiang** [comment]
I found this issue has gone in KubeSphere v3.2.1.

My S2iBuilder configuration:

```yaml
apiVersion: devops.kubesphere.io/v1alpha1
kind: S2iBuilder
metadata:
  annotations:
    kubesphere.io/creator: admin
    kubesphere.io/file: >-
      {"name":"halo-1.4.13-SNAPSHOT.war","size":84300399,"showProgress":false,"showFile":true,"percentage":100,"status":"active"}
    kubesphere.io/repoUrl: ''
    languageType: war
  finalizers:
    - s2ibuilders.finalizers.kubesphere.io
  labels:
    controller-tools.k8s.io: '1.0'
    s2i-type.kubesphere.io: b2i
  name: johnniang-halo-war-latest-3bx
  namespace: my-project
spec:
  config:
    buildVolumes:
      - 's2i_java_cache:/tmp/artifacts'
    builderImage: 'kubesphere/tomcat85-java11-centos7:v3.2.0'
    builderPullPolicy: if-not-present
    export: true
    imageName: johnniang/halo-war
    isBinaryURL: true
    outputBuildResult: true
    pushAuthentication:
      secretRef:
        name: docker-id
    revisionId: master
    runtimeArtifacts:
      - source: /deployments
    runtimeImage: 'kubesphere/tomcat85-java11-runtime:v3.2.0'
    sourceUrl: >-
      http://ks-apiserver.kubesphere-system.svc/kapis/devops.kubesphere.io/v1alpha2/namespaces/my-project/s2ibinaries/halo-1-4-13-snapshot-warkwbr/file/halo-1.4.13-SNAPSHOT.war
    tag: latest
```

and the build result:

![image](https://user-images.githubusercontent.com/16865714/147551003-77095594-8ae2-4ae8-aad4-c94a6238ce13.png)
![image](https://user-images.githubusercontent.com/16865714/147551083-2d1f3a92-540e-4aad-929c-1bd6ed90c1a8.png)

/close
