### ISSUE TITLE
Error handling PipelineRun synchronization for multi-branch pipeline

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#257]
### What happend?

I can not see any pipeline activities triggered by `Branch indexing` in GitLab pipeline.

And I found that the Pipeline synchronizer did a wrong setting on reference name, please see:

```yaml
apiVersion: devops.kubesphere.io/v1alpha3
kind: PipelineRun
metadata:
  annotations:
    devops.kubesphere.io/jenkins-pipelinerun-id: '1'
  generateName: gitlab-pipeline-
  name: gitlab-pipeline-2bf5m
  namespace: my-devops-projectsg945
spec:
  pipelineRef:
    kind: Pipeline
    name: gitlab-pipeline
    namespace: my-devops-projectsg945
  pipelineSpec:
    multi_branch_pipeline:
      discarder:
        days_to_keep: '7'
        num_to_keep: '5'
      gitlab_source:
        credential_id: gitalb-id
        discover_branches: 1
        discover_pr_from_forks:
          strategy: 2
          trust: 2
        discover_pr_from_origin: 2
        discover_tags: true
        owner: johnniang
        repo: johnniang/jenkinsfile-demo
        server_name: 'https://gitlab.com'
      name: gitlab-pipeline
      script_path: Jenkinsfile
      source_type: gitlab
    type: multi-branch-pipeline
  scm:
    refName: 'https://gitlab.com/johnniang/jenkinsfile-demo/-/merge_requests/3'
    refType: ''
```

### Steps to reproduce

1. Install KubeSphere nightly: `nightly-20210923`
1. Create a GitLab pipeline
1. See pipeline activities

/kind bug
/milestone v3.2
