### ISSUE TITLE
Failed to integrate SonarQube

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#385]
### What happened?

I'm trying to integrate SonarQube on KubeSphere 3.2.0 following [official document](https://kubesphere.com.cn/docs/devops-user-guide/how-to-integrate/sonarqube/), but something goes wrong. I always got the log below even if I restarted Deployment `devops-apiserver`:

```go
devops-apiserver-7f7f74bb56-6pn7q W1128 16:32:33.685090       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
devops-apiserver-7f7f74bb56-6pn7q W1128 16:32:33.687178       1 options.go:140] ks-apiserver starts without redis provided, it will use in memory cache. This may cause inconsistencies when running ks-apiserver with multiple replicas.
devops-apiserver-7f7f74bb56-6pn7q I1128 16:32:33.732722       1 sonarqube.go:39] Sonarqube integration is disabled
devops-apiserver-7f7f74bb56-6pn7q I1128 16:32:33.769645       1 sonarqube.go:39] Sonarqube integration is disabled
devops-apiserver-7f7f74bb56-6pn7q I1128 16:32:33.772139       1 apiserver.go:207] Start cache objects
devops-apiserver-7f7f74bb56-6pn7q I1128 16:32:33.901689       1 apiserver.go:262] Finished caching objects
devops-apiserver-7f7f74bb56-6pn7q I1128 16:32:33.902592       1 apiserver.go:171] Start listening on :9090
devops-apiserver-7f7f74bb56-6pn7q I1128 16:33:07.649188       1 apiserver.go:298] 10.233.66.210 - "GET /v1alpha2/devops/demolq7ng/pipelines/devops-maven-sample/branches/sonarqube/sonarstatus HTTP/1.1" 404 19 0ms
```

### Possible cause

At last, I figured out the reason why that didn't work.

After we edit cc `ks-installer` as below, `ks-installer` Pod will change `kubesphere-config` ConfigMap but `devops-config` won't be changed automatically.

```yaml
devops:
  enabled: true
  jenkinsJavaOpts_MaxRAM: 2g
  jenkinsJavaOpts_Xms: 512m
  jenkinsJavaOpts_Xmx: 512m
  jenkinsMemoryLim: 2Gi
  jenkinsMemoryReq: 1500Mi
  jenkinsVolumeSize: 8Gi
  sonarqube: # Add this field manually.
    externalSonarUrl: http://10.77.1.201:31377 # The SonarQube IP address.
    externalSonarToken: 00ee4c512fc987d3ec3251fdd7493193cdd3b91d # The SonarQube admin token created above.
```

/kind bug
