### ISSUE TITLE
[Proposal] Idependent Upgrade DevOps

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#425]
### Motivation

At present, the Devops backend has been separated from KubeSphere as a separate project, ks-devops. However, due to the low release frequency of KubeSphere, some problems of Devops cannot be repaired in time, which is particularly distressed for community users. In order to quickly solve the problems raised by community users as soon as possible, it is very necessary for us to launch a plan - independent upgrade Devops.

#### Goals

ks-devops is installed in Kubernetes in the form of helm charts. We only need to update helm charts and values to complete the upgrade of ks-devops.

#### Non-Goals

Separate front end of ks-devops from KubeSphere.

### Online environment upgrade example

1. Create values.yaml

   ```yaml
   image:
   apiserver:
     tag: v3.2.2
   controller:
     tag: v3.2.2
   pullPolicy: IfNotPresent
   registry: kubesphere
   tools:
     tag: v3.2.2
   ```

1. Upgrade ks-devops

   ```bash
   helm -n kubesphere-devops-system upgrade devops ks-devops --version 0.1.9 --repo https://kubesphere-sigs.github.io/ks-devops-helm-chart/ --install --reuse-values -f values.yaml
   ```

### Offline environment upgrade example

1. Create values.yaml

   ```yaml
   image:
   apiserver:
     tag: v3.2.2
   controller:
     tag: v3.2.2
   pullPolicy: IfNotPresent
   registry: kubesphere
   tools:
     tag: v3.2.2
   ```

1. Download package of ks-devops helm charts

   Download from: <https://github.com/kubesphere-sigs/ks-devops-helm-chart/releases/download/ks-devops-0.1.9/ks-devops-0.1.9.tgz>.

1. Upgrade ks-devops

   ```bash
   helm -n kubesphere-devops-system upgrade devops ./ks-devops-0.1.9.tgz --version 0.1.9 --install --reuse-values -f values.yaml
   ```

### Drawback

- Since the front end has not been separated from KubeSphere, we cannot upgrade the DevOps it using this approach.
- There are too many paramters involved and it is error-prone.
- The helm command is required on the user's operating environment.

### Alternatives

- Provides a [CLI](https://github.com/kubesphere-sigs/ks) to upgrade ks-devops with only one command.
- Create an operator of ks-devops to upgrade ks-devops

/kind proposal
