### ISSUE TITLE
Jenkins location URL is discarded while reloading CasC configuration

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/ks-devops#440]
### What happened?

After reloading existing CasC configuration under `/var/jenkins_home/casc_configs/jenkins_user.yaml`, `unclassified.location.url` is discarded.

Please see the detail of related configuration item below respectively:

- /var/jenkins_home/casc_configs/jenkins_user.yaml
```yaml
unclassified:
  location:
    url: jenkins.devops.kubesphere.local
```
- Actual CasC configuration

```yaml
unclassified:
  location:
    adminAddress: "KubeSphere <admin@example.com>"
```

/kind bug
/cc @kubesphere/sig-devops

**Comment by JohnNiang** [comment]
This doesn't block pipeline event plugin. Because I have fully ignored `url` property which may cause an exception while rendering model.

**Comment by JohnNiang** [comment]
I got the following message when Jenkins CasC was reloaded:

```java
Jan 19, 2022 8:25:53 AM INFO jenkins.model.JenkinsLocationConfiguration preventRootUrlBeingInvalid
Invalid URL received: jenkins.devops.kubesphere.local/, considered as null
```

At last, I found that Jenkins 2.319.1 check if the URL is invalid and prevent it from setting, please refer to [here](https://github.com/jenkinsci/jenkins/blob/ca0eb9119132e296db7eedecff4c823ca6c519d3/core/src/main/java/jenkins/model/JenkinsLocationConfiguration.java#L147).

So I corrected the `unclassified.location.url` configuration item and reloaded the Jenkins CasC, it worked very well and the message above was gone.

```yaml
unclassified:
  location:
    adminAddress: "KubeSphere <admin@example.com>"
    url: "http://jenkins.devops.kubesphere.local/"
```

So It would work well If we prepended `http://` for `unclassified.location.url`, please refer to
https://github.com/kubesphere-sigs/ks-devops-helm-chart/blob/8f18c01240a123f084e6a285f5966820353d8046/charts/ks-devops/charts/jenkins/templates/jenkins-casc-config.yml#L403

/good-first-issue
