### ISSUE TITLE
[Proposal] Support dynamic parameters with RESTful API in ks devops pipeline

### ISSUE THREAD

**Issue by lxm** [kubesphere/ks-devops#523]
Support dynamic parameters with RESTful API in ks devops pipeline

# Background

Currently, ks-ops support static params with pipeline. However, we need more flexible parameter generation methods in some complex scenarios.

Inspired by jenkins REST-List Parameter Plugin()[https://github.com/jenkinsci/rest-list-parameter-plugin], We can add the feature of dynamic parameters to ks-ops

# Proposal

## api

add a api to build parameters for specific pipeline
> GET /kapis/clusters/{cluster_name}/devops.kubesphere.io/v1alpha3/devops/{devops_project_name}/pipelines/{pipeline_name}/parameters

data will be returned same as current parameters key

```
[
    {
        default_value: ""
        name: ""
        type: "choice"
    }
]
```

## CRD

add parametersRef key to Pipeline CRD, support 2 kinds

* ConfigMap
* REST

```
apiVersion: devops.kubesphere.io/v1alpha3
kind: Pipeline
metadata:
  name: deploy
  namespace: deployfh9nd
spec:
  pipeline:
    discarder:
      days_to_keep: '7'
      num_to_keep: '10'
    jenkinsfile: |-
    ...
    name: deploy
    parametersRef:
      - kind: ConfigMap
        name: ks-devops-param
        valuesKey: params
        method: data/restful
    parameters:
      - default_value: |-
          image1
          image2
        name: image
        type: choice
  type: pipeline

```

# Sample Confgmaps

```
# sample config for static external param config with configmap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: user-ns
  name: pipeline-param-sample-data
data:
  parameters: |-
    - default_value: |-
            v1
            v2
      name: key2
      type: choice
    - default_value: |-
            v3
            v4
      name: key1
      type: choice
---

# sample config for dynamic external param config with configmap
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: user-ns
  name: pipeline-param-sample-request
data:
  url: "http://dyn-param.user-ns.svc:8989"
```
