### ISSUE TITLE
external jenkins  401 Unauthorized

### ISSUE THREAD

**Issue by gitzhuww** [kubesphere/ks-devops#538]
### What is version of KubeSphere DevOps has the issue?

3.2.1

### Describe this feature

devops-config 

```yaml
devops:
  host: http://192.162.5.7:8080
  maxConnections: "100"
  namespace: kubesphere-devops-system
  password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImlhdCI6MTY0OTM5MDgyOSwiaXNzIjoia3ViZXNwaGVyZSIsIm5iZiI6MTY0OTM5MDgyOX0.85dhN45U_kyf_50CbfCWPelZxYf7_Jb_QeMuYrDxR7g
  username: admin
  workerNamespace: kubesphere-devops-worker
```

this password how to make? jenkins api token ?

**Comment by gitzhuww** [comment]
![image](https://user-images.githubusercontent.com/40748699/162395113-2899db3e-e61e-4670-8126-7b438a1601d1.png)

**Comment by LinuxSuRen** [comment]
You could use the API token generated from the Jenkins user. Then add a flag to the apiserver and controller.

```
--override-jenkins-token=false
```

See also https://github.com/kubesphere/ks-devops/blob/b2362c1d0ac4f86908070d1499f8a0a79774bcdd/cmd/tools/jwt/app/jwt_root.go#L56

**Comment by gitzhuww** [comment]
> 



> You could use the API token generated from the Jenkins user. Then add a flag to the apiserver and controller.
> 
> ```
> --override-jenkins-token=false
> ```
> 
> See also
> 
> https://github.com/kubesphere/ks-devops/blob/b2362c1d0ac4f86908070d1499f8a0a79774bcdd/cmd/tools/jwt/app/jwt_root.go#L56


I set override-jenkins-token=false, but it looks like invalid。



![image](https://user-images.githubusercontent.com/40748699/162398329-d99405cb-d002-4e84-979d-144b3e43e4ac.png)

**Comment by gitzhuww** [comment]
the apiserver and controller also set --override-jenkins-token=false

**Comment by LinuxSuRen** [comment]
Please use the token from Jenkins user instead.

**Comment by gitzhuww** [comment]
> Please use the token from Jenkins user instead.

i am sure, i used jenkins api token.

**Comment by gitzhuww** [comment]
I refer to this article。
https://github.com/kubesphere/ks-devops/issues/429
but i met 401 Unauthorized

**Comment by gitzhuww** [comment]
> Please use the token from Jenkins user instead.

Using regular users is the same mistake

**Comment by gitzhuww** [comment]
> ![image](https://user-images.githubusercontent.com/40748699/162402605-a767e4da-b345-4254-9572-d6b5bcfb3271.png) devops-controller logs

@LinuxSuRen help please!  thank you!

**Comment by LinuxSuRen** [comment]
Just make sure the following fields are correct if you got 401.
```
devops:
  host: 
  password: 
  username: 
```
