### ISSUE TITLE
The CD(continuous deployment) task deployed in the member cluster runs incorrectly

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#561]
### What is version of KubeSphere DevOps has the issue?

v3.3.0-alpha.1

### What happened?

Create a CD task and select the member cluster as the deployment location.

![image](https://user-images.githubusercontent.com/68640256/164591789-1d26c5b5-b883-4c7c-a27d-b0917f2bda9d.png)
![image](https://user-images.githubusercontent.com/68640256/164591835-0f825858-eed8-49c7-a3d4-529c0db451d3.png)

```
kind: Application
apiVersion: gitops.kubesphere.io/v1alpha1
metadata:
  name: test1
  namespace: devnmqmh
  labels:
    gitops.kubesphere.io/argocd-application: test1
    gitops.kubesphere.io/argocd-location: argocd
  annotations:
    kubesphere.io/creator: admin
  finalizers:
    - application.gitops.kubesphere.io
spec:
  argoApp:
    spec:
      source:
        repoURL: 'https://github.com/wenxin-01/open-podcasts'
        path: config/default
        targetRevision: HEAD
      destination:
        server: 'https://192.168.0.3:6443'
        namespace: pro
        name: member-02
      project: devnmqmh
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
    operation:
      sync:
        revision: HEAD
        syncOptions:
          - CreateNamespace=true
      initiatedBy:
        username: admin
      retry: {}
```

/priority high
/assign @kubesphere/sig-devops
