### ISSUE TITLE
After deleting the resources created by the CD task, the deleted resources cannot be recreated using  manual synchronization.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#572]
### What is version of KubeSphere DevOps has the issue?

v3.3.0-alpha.2

### What happened?

1、There is a CD task 'gitlab-test' and sync strategy is manual sync.
```
kind: Application
apiVersion: gitops.kubesphere.io/v1alpha1
metadata:
  name: gitlab-test
  namespace: dev1tl892
  labels:
    gitops.kubesphere.io/argocd-application: gitlab-test
    gitops.kubesphere.io/argocd-location: argocd
    gitops.kubesphere.io/health-status: Healthy
    gitops.kubesphere.io/sync-status: Synced
  annotations:
    kubesphere.io/creator: admin
  finalizers:
    - application.gitops.kubesphere.io
spec:
  argoApp:
    spec:
      source:
        repoURL: 'https://gitlab.com/wxsunshine/open-podcasts.git'
        path: config/default
        targetRevision: HEAD
      destination:
        server: 'https://10.233.51.47:6443'
        namespace: pro
        name: member-01
      project: dev1tl892
```

2、Delete test project created by 'gitlab-test'
3、Manual sync the CD task 'gitlab-test'

**Expected behavior**
The deleted resources have been recreated

**Actual behavior**
The deleted resources can not be recreated

/priority high
/assign @kubesphere/sig-devops
