### ISSUE TITLE
After deleting the resources created by the CD task, the deleted resources cannot be recreated using auto synchronization

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/ks-devops#573]
### What is version of KubeSphere DevOps has the issue?

v3.3.0-alpha.2

### What happened?

1、There is a CD task 'git-test' and sync strategy is auto sync.
```
kind: Application
apiVersion: gitops.kubesphere.io/v1alpha1
metadata:
  name: git-test
  namespace: dev1tl892
  labels:
    gitops.kubesphere.io/argocd-application: git-test
    gitops.kubesphere.io/argocd-location: argocd
    gitops.kubesphere.io/health-status: Healthy
    gitops.kubesphere.io/sync-status: Synced
  annotations:
    kubesphere.io/creator: admin
  finalizers:
    - application.gitops.kubesphere.io
spec:
  argoApp:
    spec:
      source:
        repoURL: 'https://github.com/wenxin-01/open-podcasts'
        path: config/default
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: pro
        name: in-cluster
      project: dev1tl892
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
```
2、Delete test project created by 'git-test'
3、Waiting 3minutes

**Expected behavior**
The deleted resources have been recreated

**Actual behavior**
The deleted resources can not be recreated

/priority high
/assign @kubesphere/sig-devops
