### ISSUE TITLE
Request to support customize UI Pipeline steps

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#602]
## Background
Currently(before v3.3.0), [all Pipeline step UI components](https://github.com/kubesphere/console/tree/master/src/pages/devops/components/Pipeline/StepModals) belong to `.jsx` source file. So, it's not easy to add a new Pipeline step UI component if a contributor is not familiar with the relevant information.

A second big problem with the current pattern is that some steps (or commands) might be difficult for some newcomers. In some cases, some steps need a nested step. For example:

```groovy
container('base'){
  sh 'kubectl get ns'
}
```

or

```groovy
withCredentials([usernamePassword(credentialsId : "$DOCKER_CREDENTIAL_ID" ,passwordVariable : 'DOCKER_PASSWORD' ,usernameVariable : 'DOCKER_USERNAME' ,)]) {
  sh 'echo "$DOCKER_PASSWORD" | docker login $REGISTRY -u "$DOCKER_USERNAME" --password-stdin'
  sh 'docker build -f Dockerfile -t $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BUILD_NUMBER .'
  sh 'docker push $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BUILD_NUMBER'
}
```

## Proposal
Design a CRD that represents a Pipeline step. Provide an API that can list all the steps CR. Then the front-end could list all the cutomized steps.

## Actions
Firstly, we can provide some common steps. For example:

* docker login/build command
* curl command to send an HTTP request
* run kubectl command
* replace all the existing steps with the templates

## Examples
Send message to [Feishu](https://www.feishu.cn/hc/zh-CN/articles/244506653275)
```yaml
name: "Send Message to Feishu"
displayName: "Send Message to Feishu"
description: "Send Message to Feishu"
runtime: 'shell'
secret:
  required: true
  type: xxx
  wrap: true
container: 'base'
shell: |
  curl -X POST -H "Content-Type: application/json" \
    -d '{"msg_type":"text","content":{"text":".param.message"}}' \
    https://open.feishu.cn/open-apis/bot/v2/hook/$ID
parameters:
- name: message
  required: true
  display: Message to send
```

## References
* https://kubesphere.com.cn/forum/d/7330-v321
* https://github.com/kubesphere/ks-devops/issues/564
