### ISSUE TITLE
Argo CD integration request

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#63]
Currently, the KubeSphere community provides a CD solution that takes advantage of [kubernetes-cd-plugin](https://github.com/jenkinsci/kubernetes-cd-plugin). But this plugin is out-of-date and lacks maintenance. So I highly don't recommend you continue to use it.

We're looking forward to a better CD solution.

I don't have enough information for this. But [Argo CD](https://github.com/argoproj/argo-cd/) is a very popular GitOps project. Please contact us, if there's anyone who wants to help with this.

/help
/stage alpha

**Comment by LinuxSuRen** [comment]
We can expand the `devopsproject` with [the project](https://github.com/argoproj/argo-cd/blob/d0cbb1597ca8b93cae081e01c07c5c2e74f580d4/pkg/apis/application/v1alpha1/app_project_types.go#L38) of Argo CD.
```yaml
apiVersion: devops.kubesphere.io/v1alpha4
kind: devopsproject
spec:
  kind: argo-project
  resource:
    apiVersion: argoproj.io/v1alpha1
    kind: appproject
    spec:
      xxx: xx
```

Application sample:
```yaml
apiVersion: devops.kubesphere.io/v1alpha1
kind: Application
metadata:
  name: xxx
spec:
    kind: argocd-app|fluxcd|argocd-appset|argocd-app-patch
    source:
      repoURL: https://xx
      path: "/"
      targetRevision: ""
    destination:
      server: xxx
      namespace: xxx
      name: xx
    syncPolicy:
      automated:
        prune: true
        allowEmpty: true
    resource:
      apiVersion: argoproj.io/v1alpha1
      kind: ApplicationSet
      metadata:
        name: ks-devops-appset
        namespace: argocd
      spec:
        generators:
```
