### ISSUE TITLE
Request fully support containerd (runtime, building time)

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#67]
## Background
As we know, [Kubernetes can run on serval different container runtimes](https://kubernetes.io/docs/setup/production-environment/container-runtimes/). For example, it could be [containerd](https://containerd.io/), [docker](https://www.docker.com/), etc. But ks-devops can only support docker right now.

Many users start to use other container runtimes. So, I believe that it's worth it for us to support a second container runtime.

## Propose
[containerd](https://containerd.io/) was graduated from CNCF. It's a wonderful project. I recommend we support it as a second option.

## Potential actions
I didn't have too much experience in this area. So I can only provide some possible actions on this feature request.

* Support run ks-devops on containerd (I guess we don't need to do anything about this, but it's necessary to test it)
* Support build images in the Jenkins pipeline
* Provide a guide for users that don't use docker CLI to build images
  * multi-stage images building support
  * multi-arch images building support

## References
* https://containerd.io/
* https://kubesphere.com.cn/forum/d/3811-kubesphere-devops-docker
* https://kubesphere.com.cn/forum/d/3054-dockerkubernetes
* https://www.redhat.com/sysadmin/podman-inside-container

/help

**Comment by LinuxSuRen** [comment]
Considering [Podman](https://github.com/containers/podman) supports a Docker-compatible CLI interface. We will support Podman. In the meantime, a command alias can reduce the migration work for users.

`alias docker='podman'`

So, basically, users do not need to change anything.

**Comment by LinuxSuRen** [comment]
Steps to create KubeSphere via kk:

Create file `config-sample.yaml` with the following content:
```
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 192.168.0.8, internalAddress: 192.168.0.8, user: root}
  roleGroups:
    etcd:
    - node1
    master:
    - node1
    worker:
    - node1
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.19.8
    imageRepo: kubesphere
    clusterName: cluster.local
    containerManager: containerd
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []
```

Create KubeSphere cluster with `kk create cluster --filename config-sample.yaml --with-kubesphere --yes`
