### ISSUE TITLE
Support to set Kustomization parameters of an Application

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#695]

**Comment by LinuxSuRen** [comment]
Basically, this issue requests to allow users to set the parameters like the following `kustomize` part.

```yaml
spec:
  argoApp:
    spec:
      source:
        repoURL: 'https://github.com/kubesphere/console'
        path: .
        targetRevision: HEAD
        kustomize:
          namePrefix: my_
          nameSuffix: _end
          images:
            - 'nginx=nginx:latest'
          commonLabels:
            name: rick
          commonAnnotations:
            name: rick
          forceCommonLabels: true
          forceCommonAnnotations: true
```

See also https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/
