### ISSUE TITLE
Support to set image registry of Jenkins agent for improving image loading speed

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/ks-devops#757]
Let's assume there are four Kubernetes nodes, the Jenkins agent might be loaded in any of them. There's an image registry mirror (Nexus .e.g). So, we could support adding a config to let Jenkins load agent images from the image registry mirror (`localhost:9090` .e.g.).

Users could modify a ConfigMap like this:
```yaml
apiVersion: v1
data:
  agent.registry.docker.io: localhost:9090
kind: ConfigMap
  name: jenkins-agent-config
  namespace: kubesphere-devops-system
```

then, the Jenkins controller will update the CasC file as well.
