### ISSUE TITLE
create CD project in devops ui error: namespaces "mock-opcua-feature-test-branch-2" not found

### ISSUE THREAD

**Issue by zhanglc** [kubesphere/ks-devops#857]
### What is version of KubeSphere DevOps has the issue?

v3.3.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

Kubernetes 1.24.6 with RKE, and then add kubesphere

### What happened?

namespaces "mock-opcua-feature-test-branch-2" not found when use CD.

argocd config:

```yml
kind: Application
apiVersion: gitops.kubesphere.io/v1alpha1
metadata:
  name: mock-opcua-feature-test-branch-2
  namespace: mock-opcua-testqsh7r
  labels:
    gitops.kubesphere.io/argocd-application: mock-opcua-feature-test-branch-2
    gitops.kubesphere.io/argocd-location: argocd
    gitops.kubesphere.io/health-status: Healthy
    gitops.kubesphere.io/sync-status: Synced
  annotations:
    kubesphere.io/creator: admin
  finalizers:
    - application.gitops.kubesphere.io
spec:
  argoApp:
    spec:
      source:
        repoURL: >-
          https://gitlab.com/iconnector-mock-opcua.git
        path: .k8s/overlays/feature-test-branch-2
        targetRevision: feature/test-branch-2
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
        name: in-cluster
      project: mock-opcua-testqsh7r
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=false
```

namespace: mock-opcua-feature-test-branch-2 is setting by `kustomize`

```code
apiVersion: v1
data:
  config.file: |-
    spring:
      datasource:
        url: jdbc:postgresql://postgres-service:5432/mock_opcua
        username: standalone
        password: bfXa4Pt2lUUScy8jakXf
        driverClassName: org.postgresql.Driver
kind: ConfigMap
metadata:
  name: app-config-2g487tghmd
  namespace: mock-opcua-feature-test-branch-2
---
apiVersion: v1
data:
  postgres.init: |-
    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    create database mock_opcua
        with owner standalone;


    create table historical_data
    (
        id          serial
            primary key,
        identifier  varchar(50),
        record_time timestamp with time zone,
        electronics double precision default 0,
        factory     varchar(20)
    );

    alter table historical_data
        owner to standalone;

    create index historical_data_identifier_record_time_index
        on historical_data (identifier, record_time);
    EOSQL
  postgres.password: bfXa4Pt2lUUScy8jakXf
  postgres.user: standalone
kind: ConfigMap
metadata:
  name: postgres-config-8kkgmkmd42
  namespace: mock-opcua-feature-test-branch-2
---
apiVersion: v1
kind: Service
metadata:
  name: mock-opcua-server-service
  namespace: mock-opcua-feature-test-branch-2
spec:
  ports:
  - port: 32333
    targetPort: 32333
  selector:
    app: mock-opcua-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: mock-opcua-feature-test-branch-2
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mock-opcua-feature-test-branch-2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-opcua-server-deployment
  namespace: mock-opcua-feature-test-branch-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-opcua-server
  template:
    metadata:
      labels:
        app: mock-opcua-server
    spec:
      containers:
      - image: docker.io/mock-opcua:a498b551
        name: mock-opcua-server
        ports:
        - containerPort: 32333
        volumeMounts:
        - mountPath: /app/application.yml
          name: config-volume
          subPath: config.file
      volumes:
      - configMap:
          name: app-config-2g487tghmd
        name: config-volume
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: mock-opcua-feature-test-branch-2
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: postgres.user
              name: postgres-config-8kkgmkmd42
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: postgres.password
              name: postgres-config-8kkgmkmd42
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        image: postgres:13.8-alpine
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
        - mountPath: /docker-entrypoint-initdb.d/init-user-db.sh
          name: config-volume
          subPath: postgres.init
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - configMap:
          name: postgres-config-8kkgmkmd42
        name: config-volume
```

![image](https://user-images.githubusercontent.com/4049133/204428368-94997052-04d8-40e9-81ba-d9f1ba7e5e11.png)

### Relevant log output

```shell
I1129 02:13:36.450013       1 argocd-application-status-controller.go:51] ArgoCDApplicationStatusController "msg"="start to reconcile ArgoCD application: argocd/mock-opcua-feature-test-branch-2"  

 E1129 02:13:36.459504       1 controller.go:246] controller "msg"="Reconciler error" "error"="Operation cannot be fulfilled on applications.gitops.kubesphere.io \"mock-opcua-feature-test-branch-2\": the object has been modified; please apply your changes to the latest version and try again" "controller"="application" "name"="mock-opcua-feature-test-branch-2" "namespace"="argocd" "reconcilerGroup"="argoproj.io" "reconcilerKind"="Application"
```

### Additional information

```markdown
no
```
