### ISSUE TITLE
devops creates deployment under unexpected namespace 

### ISSUE THREAD

**Issue by umialpha** [kubesphere/ks-devops#866]
### What is version of KubeSphere DevOps has the issue?

v3.3.1

### How did you install the Kubernetes? Or what is the Kubernetes distribution?

ksinstall

### What happened?

I create a cd in devops project, here is the yaml file 
```yaml
kind: Application
apiVersion: gitops.kubesphere.io/v1alpha1
metadata:
  name: devops
  namespace: dev-testjbwcl
  labels:
    gitops.kubesphere.io/argocd-application: devops
    gitops.kubesphere.io/argocd-location: argocd
    gitops.kubesphere.io/health-status: Healthy
    gitops.kubesphere.io/sync-status: Synced
  annotations:
    kubesphere.io/creator: admin
  finalizers:
    - application.gitops.kubesphere.io
spec:
  argoApp:
    spec:
      source:
        repoURL: 'https://github.com/kubesphere-sigs/open-podcasts'
        path: config/default
        targetRevision: HEAD
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: test
        name: in-cluster
      project: dev-testjbwcl
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true
          - Replace=true
          - PrunePropagationPolicy=background
```
i expect it should be deployed under project `test`, as the picture also indicates 
<img width="270" alt="image" src="https://user-images.githubusercontent.com/13465150/206346033-47657f98-0c28-471a-a68b-2eda4a03182b.png">

But when i enter the project `test`, nothing to be found. So I double check the demo repo `https://github.com/kubesphere-sigs/open-podcasts/blob/master/config/default/kustomization.yaml`, find it is deployed under namespace `osf2f-system`.  

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/13465150/206346780-5b8f831b-2581-478b-b2aa-8bd0e18bfca8.png">
 
Indeed, it is under project `osf2f-system`, but it should be in project`test`, right?
